// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReteteInternationale.API.Data;

#nullable disable

namespace Aplicatie.API.Migrations
{
    [DbContext(typeof(AplicatieDbContext))]
    partial class AplicatieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aplicatie.API.Models.Comentariu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RetetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UtilizatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RetetaId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Comentarii");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RetetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UtilizatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RetetaId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaraId");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Reteta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagineUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingrediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("TaraId");

                    b.ToTable("Retete");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Tara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tari");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Utilizator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Comentariu", b =>
                {
                    b.HasOne("Aplicatie.API.Models.Reteta", "Reteta")
                        .WithMany("Comentarii")
                        .HasForeignKey("RetetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicatie.API.Models.Utilizator", "Utilizator")
                        .WithMany("Comentarii")
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reteta");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Favorite", b =>
                {
                    b.HasOne("Aplicatie.API.Models.Reteta", "Reteta")
                        .WithMany("Favorite")
                        .HasForeignKey("RetetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicatie.API.Models.Utilizator", "Utilizator")
                        .WithMany("Favorite")
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reteta");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Restaurant", b =>
                {
                    b.HasOne("Aplicatie.API.Models.Tara", "Tara")
                        .WithMany()
                        .HasForeignKey("TaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tara");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Reteta", b =>
                {
                    b.HasOne("Aplicatie.API.Models.Restaurant", null)
                        .WithMany("Retete")
                        .HasForeignKey("RestaurantId");

                    b.HasOne("Aplicatie.API.Models.Tara", "Tara")
                        .WithMany("Retete")
                        .HasForeignKey("TaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tara");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Restaurant", b =>
                {
                    b.Navigation("Retete");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Reteta", b =>
                {
                    b.Navigation("Comentarii");

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Tara", b =>
                {
                    b.Navigation("Retete");
                });

            modelBuilder.Entity("Aplicatie.API.Models.Utilizator", b =>
                {
                    b.Navigation("Comentarii");

                    b.Navigation("Favorite");
                });
#pragma warning restore 612, 618
        }
    }
}
